[
    {
        "url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/4174",
        "repository_url": "https://api.github.com/repos/mitmproxy/mitmproxy",
        "labels_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/4174/labels{/name}",
        "comments_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/4174/comments",
        "events_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/4174/events",
        "html_url": "https://github.com/mitmproxy/mitmproxy/pull/4174",
        "id": 686676993,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDc0MjEwMjU3",
        "number": 4174,
        "title": "Python 3.9 Compatibility",
        "user": {
            "login": "mhils",
            "id": 1019198,
            "node_id": "MDQ6VXNlcjEwMTkxOTg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1019198?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mhils",
            "html_url": "https://github.com/mhils",
            "followers_url": "https://api.github.com/users/mhils/followers",
            "following_url": "https://api.github.com/users/mhils/following{/other_user}",
            "gists_url": "https://api.github.com/users/mhils/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mhils/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mhils/subscriptions",
            "organizations_url": "https://api.github.com/users/mhils/orgs",
            "repos_url": "https://api.github.com/users/mhils/repos",
            "events_url": "https://api.github.com/users/mhils/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mhils/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2020-08-26T21:57:31Z",
        "updated_at": "2020-10-06T20:41:59Z",
        "closed_at": "2020-10-06T20:41:56Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mitmproxy/mitmproxy/pulls/4174",
            "html_url": "https://github.com/mitmproxy/mitmproxy/pull/4174",
            "diff_url": "https://github.com/mitmproxy/mitmproxy/pull/4174.diff",
            "patch_url": "https://github.com/mitmproxy/mitmproxy/pull/4174.patch"
        },
        "body": "Current Status:\r\n\r\n - [x] Windows: Working. ~fails because of missing cryptography wheels~\r\n - [x] Linux: fails when importing passlib 1.7.2 (https://foss.heptapod.net/python-libs/passlib/-/issues/126)\r\n - [x] macOS: Working. ~fails with [`TypeError: Subscripted generics cannot be used with class and instance checks`](https://github.com/mitmproxy/mitmproxy/pull/4174/checks?check_run_id=1033827835) (see #4021)~",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2488",
        "repository_url": "https://api.github.com/repos/mitmproxy/mitmproxy",
        "labels_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2488/labels{/name}",
        "comments_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2488/comments",
        "events_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2488/events",
        "html_url": "https://github.com/mitmproxy/mitmproxy/pull/2488",
        "id": 246762430,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTMzMjUwMTk5",
        "number": 2488,
        "title": "Fix minor typing mistake in mitmproxy/tools/main.py",
        "user": {
            "login": "MatthewShao",
            "id": 9366279,
            "node_id": "MDQ6VXNlcjkzNjYyNzk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9366279?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MatthewShao",
            "html_url": "https://github.com/MatthewShao",
            "followers_url": "https://api.github.com/users/MatthewShao/followers",
            "following_url": "https://api.github.com/users/MatthewShao/following{/other_user}",
            "gists_url": "https://api.github.com/users/MatthewShao/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MatthewShao/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MatthewShao/subscriptions",
            "organizations_url": "https://api.github.com/users/MatthewShao/orgs",
            "repos_url": "https://api.github.com/users/MatthewShao/repos",
            "events_url": "https://api.github.com/users/MatthewShao/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MatthewShao/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2017-07-31T13:51:15Z",
        "updated_at": "2017-07-31T13:53:52Z",
        "closed_at": "2017-07-31T13:53:52Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mitmproxy/mitmproxy/pulls/2488",
            "html_url": "https://github.com/mitmproxy/mitmproxy/pull/2488",
            "diff_url": "https://github.com/mitmproxy/mitmproxy/pull/2488.diff",
            "patch_url": "https://github.com/mitmproxy/mitmproxy/pull/2488.patch"
        },
        "body": "`mitmproxy` and `mitmweb` failed to start with following error message:\r\n```\r\nTraceback (most recent call last):\r\n  File \"/home/matthew/mitmproxy/venv/bin/mitmproxy\", line 11, in <module>\r\n    load_entry_point('mitmproxy', 'console_scripts', 'mitmproxy')()\r\n  File \"/home/matthew/mitmproxy/mitmproxy/tools/main.py\", line 127, in mitmproxy\r\n    run(console.master.ConsoleMaster, cmdline.mitmproxy, args)\r\n  File \"/home/matthew/mitmproxy/mitmproxy/tools/main.py\", line 103, in run\r\n    opts.update(**extra(args))\r\n  File \"/usr/lib/python3.5/typing.py\", line 135, in __new__\r\n    raise TypeError(\"Cannot instantiate %r\" % self.__class__)\r\nTypeError: Cannot instantiate <class 'typing.CallableMeta'>\r\n```\r\nIt was caused by the error syntax of the default value, this PR should fix that.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2325",
        "repository_url": "https://api.github.com/repos/mitmproxy/mitmproxy",
        "labels_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2325/labels{/name}",
        "comments_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2325/comments",
        "events_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/2325/events",
        "html_url": "https://github.com/mitmproxy/mitmproxy/pull/2325",
        "id": 227431437,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTE5NzA1MTA0",
        "number": 2325,
        "title": "Handle head request on onboarding app: Fix #2324",
        "user": {
            "login": "ujjwal96",
            "id": 16747982,
            "node_id": "MDQ6VXNlcjE2NzQ3OTgy",
            "avatar_url": "https://avatars.githubusercontent.com/u/16747982?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ujjwal96",
            "html_url": "https://github.com/ujjwal96",
            "followers_url": "https://api.github.com/users/ujjwal96/followers",
            "following_url": "https://api.github.com/users/ujjwal96/following{/other_user}",
            "gists_url": "https://api.github.com/users/ujjwal96/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ujjwal96/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ujjwal96/subscriptions",
            "organizations_url": "https://api.github.com/users/ujjwal96/orgs",
            "repos_url": "https://api.github.com/users/ujjwal96/repos",
            "events_url": "https://api.github.com/users/ujjwal96/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ujjwal96/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2017-05-09T16:55:03Z",
        "updated_at": "2017-05-09T18:09:59Z",
        "closed_at": "2017-05-09T18:08:43Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mitmproxy/mitmproxy/pulls/2325",
            "html_url": "https://github.com/mitmproxy/mitmproxy/pull/2325",
            "diff_url": "https://github.com/mitmproxy/mitmproxy/pull/2325.diff",
            "patch_url": "https://github.com/mitmproxy/mitmproxy/pull/2325.patch"
        },
        "body": "fixes #2324\r\n\r\n@Kriechi The test is failing sometimes on my local machine.\r\nIt throws a TypeError `TypeError: getsockaddrarg() takes exactly 2 arguments (4 given)` in tcp.create_connection on [this line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/tcp.py#L668) when the af is AF_INET and source address is ('::1', 52418, 0, 0) \r\nIs it something wrong wtih the test or create_connection function? \r\nNone of the other test fail :confused: ",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1563",
        "repository_url": "https://api.github.com/repos/mitmproxy/mitmproxy",
        "labels_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1563/labels{/name}",
        "comments_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1563/comments",
        "events_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1563/events",
        "html_url": "https://github.com/mitmproxy/mitmproxy/pull/1563",
        "id": 178504910,
        "node_id": "MDExOlB1bGxSZXF1ZXN0ODYyNzA5OTA=",
        "number": 1563,
        "title": "Raise TypeError on invalid header assignment, fix #1562",
        "user": {
            "login": "mhils",
            "id": 1019198,
            "node_id": "MDQ6VXNlcjEwMTkxOTg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1019198?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mhils",
            "html_url": "https://github.com/mhils",
            "followers_url": "https://api.github.com/users/mhils/followers",
            "following_url": "https://api.github.com/users/mhils/following{/other_user}",
            "gists_url": "https://api.github.com/users/mhils/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mhils/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mhils/subscriptions",
            "organizations_url": "https://api.github.com/users/mhils/orgs",
            "repos_url": "https://api.github.com/users/mhils/repos",
            "events_url": "https://api.github.com/users/mhils/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mhils/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-09-22T02:22:18Z",
        "updated_at": "2016-09-22T04:00:07Z",
        "closed_at": "2016-09-22T04:00:07Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mitmproxy/mitmproxy/pulls/1563",
            "html_url": "https://github.com/mitmproxy/mitmproxy/pull/1563",
            "diff_url": "https://github.com/mitmproxy/mitmproxy/pull/1563.diff",
            "patch_url": "https://github.com/mitmproxy/mitmproxy/pull/1563.patch"
        },
        "body": "",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1558",
        "repository_url": "https://api.github.com/repos/mitmproxy/mitmproxy",
        "labels_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1558/labels{/name}",
        "comments_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1558/comments",
        "events_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1558/events",
        "html_url": "https://github.com/mitmproxy/mitmproxy/pull/1558",
        "id": 177586627,
        "node_id": "MDExOlB1bGxSZXF1ZXN0ODU2NzgxMTE=",
        "number": 1558,
        "title": "Update app.py",
        "user": {
            "login": "vulnminer",
            "id": 22220456,
            "node_id": "MDQ6VXNlcjIyMjIwNDU2",
            "avatar_url": "https://avatars.githubusercontent.com/u/22220456?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vulnminer",
            "html_url": "https://github.com/vulnminer",
            "followers_url": "https://api.github.com/users/vulnminer/followers",
            "following_url": "https://api.github.com/users/vulnminer/following{/other_user}",
            "gists_url": "https://api.github.com/users/vulnminer/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vulnminer/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vulnminer/subscriptions",
            "organizations_url": "https://api.github.com/users/vulnminer/orgs",
            "repos_url": "https://api.github.com/users/vulnminer/repos",
            "events_url": "https://api.github.com/users/vulnminer/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vulnminer/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-09-17T15:52:23Z",
        "updated_at": "2016-09-17T16:36:41Z",
        "closed_at": "2016-09-17T16:36:41Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mitmproxy/mitmproxy/pulls/1558",
            "html_url": "https://github.com/mitmproxy/mitmproxy/pull/1558",
            "diff_url": "https://github.com/mitmproxy/mitmproxy/pull/1558.diff",
            "patch_url": "https://github.com/mitmproxy/mitmproxy/pull/1558.patch"
        },
        "body": " (Mac os X yosemite)\n\nFixes error:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.5/site-packages/tornado-4.4.1-py3.5-macosx-10.11-x86_64.egg/tornado/web.py\", line 1467, in _execute\n    result = method(_self.path_args, *_self.path_kwargs)\n  File \"/Users/<user>/Desktop/mitmproxy/mitmproxy/web/app.py\", line 390, in put\n    for k, v in six.iteritems(self.json):\n  File \"/Users/<user>/Desktop/mitmproxy/mitmproxy/web/app.py\", line 119, in json\n    return json.loads(self.request.body)\n  File \"/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py\", line 312, in loads\n    s.**class**.**name**))\nTypeError: the JSON object must be str, not 'bytes'\nERROR:tornado.access:500 PUT /settings ...\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1199",
        "repository_url": "https://api.github.com/repos/mitmproxy/mitmproxy",
        "labels_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1199/labels{/name}",
        "comments_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1199/comments",
        "events_url": "https://api.github.com/repos/mitmproxy/mitmproxy/issues/1199/events",
        "html_url": "https://github.com/mitmproxy/mitmproxy/pull/1199",
        "id": 158232904,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NzI0MTI1Mzg=",
        "number": 1199,
        "title": "Handle the slice object case in TransformGenerator.__getitem__",
        "user": {
            "login": "dufferzafar",
            "id": 1449512,
            "node_id": "MDQ6VXNlcjE0NDk1MTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1449512?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dufferzafar",
            "html_url": "https://github.com/dufferzafar",
            "followers_url": "https://api.github.com/users/dufferzafar/followers",
            "following_url": "https://api.github.com/users/dufferzafar/following{/other_user}",
            "gists_url": "https://api.github.com/users/dufferzafar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/dufferzafar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dufferzafar/subscriptions",
            "organizations_url": "https://api.github.com/users/dufferzafar/orgs",
            "repos_url": "https://api.github.com/users/dufferzafar/repos",
            "events_url": "https://api.github.com/users/dufferzafar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/dufferzafar/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-06-02T20:32:20Z",
        "updated_at": "2016-06-02T20:47:30Z",
        "closed_at": "2016-06-02T20:45:56Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/mitmproxy/mitmproxy/pulls/1199",
            "html_url": "https://github.com/mitmproxy/mitmproxy/pull/1199",
            "diff_url": "https://github.com/mitmproxy/mitmproxy/pull/1199.diff",
            "patch_url": "https://github.com/mitmproxy/mitmproxy/pull/1199.patch"
        },
        "body": "should fix https://travis-ci.org/mitmproxy/mitmproxy/jobs/134827120#L501 test failures:\n\n```\nself = <netlib.websockets.protocol.Masker object at 0x7fe8ebdfc110>\noffset = slice(0, 3, None), data = 'foo'\n    def mask(self, offset, data):\n        result = bytearray(data)\n        if six.PY2:\n            for i in range(len(data)):\n>               result[i] ^= ord(self.key[offset % 4])\nE               TypeError: unsupported operand type(s) for %: 'slice' and 'int'\nnetlib/websockets/protocol.py:47: TypeError\n```\n",
        "performed_via_github_app": null,
        "score": 1.0
    }
]