[
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/9725",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/9725/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/9725/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/9725/events",
        "html_url": "https://github.com/tensorflow/models/pull/9725",
        "id": 805175352,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NTcwODIzMzcz",
        "number": 9725,
        "title": "[object detection] Bug fixes in colab tutorial",
        "user": {
            "login": "tylerganter",
            "id": 9789052,
            "node_id": "MDQ6VXNlcjk3ODkwNTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9789052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tylerganter",
            "html_url": "https://github.com/tylerganter",
            "followers_url": "https://api.github.com/users/tylerganter/followers",
            "following_url": "https://api.github.com/users/tylerganter/following{/other_user}",
            "gists_url": "https://api.github.com/users/tylerganter/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tylerganter/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tylerganter/subscriptions",
            "organizations_url": "https://api.github.com/users/tylerganter/orgs",
            "repos_url": "https://api.github.com/users/tylerganter/repos",
            "events_url": "https://api.github.com/users/tylerganter/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tylerganter/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 5,
        "created_at": "2021-02-10T05:11:54Z",
        "updated_at": "2021-04-23T17:11:06Z",
        "closed_at": "2021-04-20T20:08:01Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/9725",
            "html_url": "https://github.com/tensorflow/models/pull/9725",
            "diff_url": "https://github.com/tensorflow/models/pull/9725.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/9725.patch"
        },
        "body": "# Description\r\n\r\nModifying the `object_detection_tutorial.ipynb` colab tutorial to work with a fresh colab environment.\r\n\r\nMost of these changes are pretty straight forward. The exception is the change to `utils/ops.py`. This is an issue with types, where tensorflow can better handle different numpy types than the other way around:\r\n```python\r\nimport numpy as np\r\nimport tensorflow as tf\r\n\r\ntf.uint8 == np.uint8\r\n# True\r\n\r\ntf.uint8 == np.dtype(\"uint8\")\r\n# True\r\n\r\nnp.uint8 == tf.uint8\r\n# True\r\n\r\nnp.dtype(\"uint8\") == tf.uint8\r\n# TypeError: Cannot interpret 'tf.uint8' as a data type\r\n```\r\n\r\n## Type of change\r\n\r\n- [X] Bug fix (non-breaking change which fixes an issue)\r\n\r\n## Tests\r\n\r\nLoading this notebook into a fresh colab environment, all cells will succeed.\r\n\r\n**Note**: there is a caveat that the change in `research/object_detection/utils/ops.py ` will not propagate to the notebook.\r\nAn alternative solution that will work for testing is to cast the detection masks via:\r\n```python\r\ntf.convert_to_tensor(output_dict['detection_masks'])\r\n```\r\n\r\n## Checklist\r\n\r\n- [X] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).\r\n- [X] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).\r\n- [X] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).\r\n- [X] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.\r\n- [X] I have commented my code, particularly in hard-to-understand areas.\r\n- [X] I have made corresponding changes to the documentation.\r\n- [X] My changes generate no new warnings.\r\n- [X] I have added tests that prove my fix is effective or that my feature works.\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/8722",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/8722/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/8722/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/8722/events",
        "html_url": "https://github.com/tensorflow/models/pull/8722",
        "id": 643904252,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NDM4NjIxMzQ3",
        "number": 8722,
        "title": "Fix TypeError when calculating normalized_error",
        "user": {
            "login": "ian-cannon",
            "id": 50238327,
            "node_id": "MDQ6VXNlcjUwMjM4MzI3",
            "avatar_url": "https://avatars.githubusercontent.com/u/50238327?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ian-cannon",
            "html_url": "https://github.com/ian-cannon",
            "followers_url": "https://api.github.com/users/ian-cannon/followers",
            "following_url": "https://api.github.com/users/ian-cannon/following{/other_user}",
            "gists_url": "https://api.github.com/users/ian-cannon/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ian-cannon/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ian-cannon/subscriptions",
            "organizations_url": "https://api.github.com/users/ian-cannon/orgs",
            "repos_url": "https://api.github.com/users/ian-cannon/repos",
            "events_url": "https://api.github.com/users/ian-cannon/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ian-cannon/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2020-06-23T14:45:48Z",
        "updated_at": "2020-06-23T15:22:56Z",
        "closed_at": "2020-06-23T15:18:48Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/8722",
            "html_url": "https://github.com/tensorflow/models/pull/8722",
            "diff_url": "https://github.com/tensorflow/models/pull/8722.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/8722.patch"
        },
        "body": "Update agent.py according to changes noted https://github.com/tensorflow/models/issues/7719 \r\nto overcome the following error:\r\n`TypeError: x and y must have the same dtype, got tf.float32 != tf.float64\r\n  In call to configurable 'train_uvf' (<function train_uvf at 0x7f0b2e5ef320>)`\r\n\r\n# Description\r\n\r\n> :memo: Please include a summary of the change. \r\n>  \r\n> * Please also include relevant motivation and context.  \r\n> * List any dependencies that are required for this change.  \r\n\r\n## Type of change\r\n\r\nFor a new feature or function, please create an issue first to discuss it\r\nwith us before submitting a pull request.\r\n\r\nNote: Please delete options that are not relevant.\r\n\r\n- [x] Bug fix (non-breaking change which fixes an issue)\r\n- [ ] Documentation update\r\n- [ ] TensorFlow 2 migration\r\n- [ ] New feature (non-breaking change which adds functionality)\r\n- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)\r\n- [ ] A new research paper code implementation\r\n- [ ] Other (Specify)\r\n\r\n## Tests\r\n\r\n> :memo: Please describe the tests that you ran to verify your changes.\r\n>  \r\n> * Provide instructions so we can reproduce.  \r\n> * Please also list any relevant details for your test configuration.  \r\n\r\n**Test Configuration**:\r\n\r\n## Checklist\r\n\r\n- [x] I have signed the [Contributor License Agreement](https://github.com/tensorflow/models/wiki/Contributor-License-Agreements).\r\n- [x] I have read [guidelines for pull request](https://github.com/tensorflow/models/wiki/Submitting-a-pull-request).\r\n- [x] My code follows the [coding guidelines](https://github.com/tensorflow/models/wiki/Coding-guidelines).\r\n- [x] I have performed a self [code review](https://github.com/tensorflow/models/wiki/Code-review) of my own code.\r\n- [x] I have commented my code, particularly in hard-to-understand areas.\r\n- [ ] I have made corresponding changes to the documentation.\r\n- [x] My changes generate no new warnings.\r\n- [ ] I have added tests that prove my fix is effective or that my feature works.\r\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/7227",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/7227/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/7227/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/7227/events",
        "html_url": "https://github.com/tensorflow/models/pull/7227",
        "id": 468749540,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mjk4MTE4NTQ2",
        "number": 7227,
        "title": "Fix for #7225: CIFAR-10 eval fails with error TypeError: Input 'predictions' of 'InTopKV2' Op has type float16 that contributed by mattmann.",
        "user": {
            "login": "chrismattmann",
            "id": 395887,
            "node_id": "MDQ6VXNlcjM5NTg4Nw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/395887?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/chrismattmann",
            "html_url": "https://github.com/chrismattmann",
            "followers_url": "https://api.github.com/users/chrismattmann/followers",
            "following_url": "https://api.github.com/users/chrismattmann/following{/other_user}",
            "gists_url": "https://api.github.com/users/chrismattmann/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/chrismattmann/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/chrismattmann/subscriptions",
            "organizations_url": "https://api.github.com/users/chrismattmann/orgs",
            "repos_url": "https://api.github.com/users/chrismattmann/repos",
            "events_url": "https://api.github.com/users/chrismattmann/events{/privacy}",
            "received_events_url": "https://api.github.com/users/chrismattmann/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2019-07-16T16:24:00Z",
        "updated_at": "2020-03-10T19:03:30Z",
        "closed_at": "2019-07-18T20:14:56Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/7227",
            "html_url": "https://github.com/tensorflow/models/pull/7227",
            "diff_url": "https://github.com/tensorflow/models/pull/7227.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/7227.patch"
        },
        "body": null,
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/6940",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/6940/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/6940/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/6940/events",
        "html_url": "https://github.com/tensorflow/models/pull/6940",
        "id": 451011525,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mjg0MjE3ODIy",
        "number": 6940,
        "title": "absl_app.run() fails without including `main` as an argument",
        "user": {
            "login": "dwightjl",
            "id": 8083094,
            "node_id": "MDQ6VXNlcjgwODMwOTQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8083094?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dwightjl",
            "html_url": "https://github.com/dwightjl",
            "followers_url": "https://api.github.com/users/dwightjl/followers",
            "following_url": "https://api.github.com/users/dwightjl/following{/other_user}",
            "gists_url": "https://api.github.com/users/dwightjl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/dwightjl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dwightjl/subscriptions",
            "organizations_url": "https://api.github.com/users/dwightjl/orgs",
            "repos_url": "https://api.github.com/users/dwightjl/repos",
            "events_url": "https://api.github.com/users/dwightjl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/dwightjl/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-05-31T23:11:41Z",
        "updated_at": "2019-06-03T16:02:52Z",
        "closed_at": "2019-06-03T16:02:51Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/6940",
            "html_url": "https://github.com/tensorflow/models/pull/6940",
            "diff_url": "https://github.com/tensorflow/models/pull/6940.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/6940.patch"
        },
        "body": "After the change (https://github.com/tensorflow/models/pull/6846/files#diff-965780bf33f2aeca41a33f8eba197c79) I receive the following error:\r\n\r\nFile \"./models/official/mnist/mnist_tpu.py\", line 202, in <module>\r\n    absl_app.run()\r\nTypeError: run() missing 1 required positional argument: 'main'\r\n\r\nI added main as an argument and it seems to be working fine now.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/7061",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/7061/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/7061/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/7061/events",
        "html_url": "https://github.com/tensorflow/models/pull/7061",
        "id": 458299157,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Mjg5OTM3MTgy",
        "number": 7061,
        "title": "Transformer xla  and FP16 benchmarks",
        "user": {
            "login": "tfboyd",
            "id": 23486130,
            "node_id": "MDQ6VXNlcjIzNDg2MTMw",
            "avatar_url": "https://avatars.githubusercontent.com/u/23486130?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tfboyd",
            "html_url": "https://github.com/tfboyd",
            "followers_url": "https://api.github.com/users/tfboyd/followers",
            "following_url": "https://api.github.com/users/tfboyd/following{/other_user}",
            "gists_url": "https://api.github.com/users/tfboyd/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tfboyd/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tfboyd/subscriptions",
            "organizations_url": "https://api.github.com/users/tfboyd/orgs",
            "repos_url": "https://api.github.com/users/tfboyd/repos",
            "events_url": "https://api.github.com/users/tfboyd/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tfboyd/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-06-20T02:03:13Z",
        "updated_at": "2019-06-25T15:37:42Z",
        "closed_at": "2019-06-20T03:19:28Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/7061",
            "html_url": "https://github.com/tensorflow/models/pull/7061",
            "diff_url": "https://github.com/tensorflow/models/pull/7061.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/7061.patch"
        },
        "body": "FP16 test are failing.\r\n\r\nTypeError: in converted code:\r\n\r\n   /workspace/benchmarks/perfzero/workspace/site-packages/models/official/transformer/v2/transformer.py:127 call  *\r\n       logits = self.decode(targets, encoder_outputs, attention_bias, training)\r\n   /workspace/benchmarks/perfzero/workspace/site-packages/models/official/transformer/v2/transformer.py:206 decode  *\r\n       logits = self.embedding_softmax_layer(outputs, mode=\"linear\")\r\n   /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:699 __call__\r\n       outputs = call_fn(inputs, *args, **kwargs)\r\n   /workspace/benchmarks/perfzero/workspace/site-packages/models/official/transformer/v2/embedding_layer.py:73 call  *\r\n       return self._linear(inputs)\r\n   /workspace/benchmarks/perfzero/workspace/site-packages/models/official/transformer/v2/embedding_layer.py:102 _linear  *\r\n       logits = tf.matmul(x, self.shared_weights, transpose_b=True)\r\n   /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py:180 wrapper\r\n       return target(*args, **kwargs)\r\n   /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py:2661 matmul\r\n       a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)\r\n   /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_math_ops.py:5982 mat_mul\r\n       name=name)\r\n   /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py:563 _apply_op_helper\r\n       inferred_from[input_arg.type_attr]))\r\n\r\n   TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type float16 of argument 'a'.\r\nhttps://sponge.corp.google.com/target?id=db890010-cb81-44ce-a74e-2a33cc500e74&target=tensorflow_models/perfzero/manual/v100_1_gpu/v100_1_gpu&searchFor=&show=ALL&sortBy=STATUS\r\nchecking to see if I did anything wrong.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/6049",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/6049/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/6049/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/6049/events",
        "html_url": "https://github.com/tensorflow/models/pull/6049",
        "id": 399167784,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjQ0NjU5ODE5",
        "number": 6049,
        "title": "Transformer: Stop crashing at the end of training phase.",
        "user": {
            "login": "wangtz",
            "id": 34290063,
            "node_id": "MDQ6VXNlcjM0MjkwMDYz",
            "avatar_url": "https://avatars.githubusercontent.com/u/34290063?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wangtz",
            "html_url": "https://github.com/wangtz",
            "followers_url": "https://api.github.com/users/wangtz/followers",
            "following_url": "https://api.github.com/users/wangtz/following{/other_user}",
            "gists_url": "https://api.github.com/users/wangtz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wangtz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wangtz/subscriptions",
            "organizations_url": "https://api.github.com/users/wangtz/orgs",
            "repos_url": "https://api.github.com/users/wangtz/repos",
            "events_url": "https://api.github.com/users/wangtz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wangtz/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2019-01-15T02:58:40Z",
        "updated_at": "2019-01-16T05:37:01Z",
        "closed_at": "2019-01-15T18:24:55Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/6049",
            "html_url": "https://github.com/tensorflow/models/pull/6049",
            "diff_url": "https://github.com/tensorflow/models/pull/6049.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/6049.patch"
        },
        "body": "It currently fails with\r\nTypeError: not all arguments converted during string formatting",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/5505",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/5505/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/5505/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/5505/events",
        "html_url": "https://github.com/tensorflow/models/pull/5505",
        "id": 369309064,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjIyMjgyNzgz",
        "number": 5505,
        "title": "Prevents TypeError:'dict_keys' object does not support indexing",
        "user": {
            "login": "bapfeld",
            "id": 17340419,
            "node_id": "MDQ6VXNlcjE3MzQwNDE5",
            "avatar_url": "https://avatars.githubusercontent.com/u/17340419?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bapfeld",
            "html_url": "https://github.com/bapfeld",
            "followers_url": "https://api.github.com/users/bapfeld/followers",
            "following_url": "https://api.github.com/users/bapfeld/following{/other_user}",
            "gists_url": "https://api.github.com/users/bapfeld/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bapfeld/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bapfeld/subscriptions",
            "organizations_url": "https://api.github.com/users/bapfeld/orgs",
            "repos_url": "https://api.github.com/users/bapfeld/repos",
            "events_url": "https://api.github.com/users/bapfeld/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bapfeld/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2018-10-11T21:18:17Z",
        "updated_at": "2018-10-11T21:30:49Z",
        "closed_at": "2018-10-11T21:30:49Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/5505",
            "html_url": "https://github.com/tensorflow/models/pull/5505",
            "diff_url": "https://github.com/tensorflow/models/pull/5505.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/5505.patch"
        },
        "body": "The preprocessing script in skip_thoughts fails with Python3.6 because collections.Counter() keys and values return DictKey objects, throwing throws a TypeError. I believe this fix should be compatible with both Python 2.6.x and Python3.x",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/5777",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/5777/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/5777/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/5777/events",
        "html_url": "https://github.com/tensorflow/models/pull/5777",
        "id": 382223218,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjMxOTc5NTM0",
        "number": 5777,
        "title": "Update running_pets.md",
        "user": {
            "login": "Vyas9296",
            "id": 19590865,
            "node_id": "MDQ6VXNlcjE5NTkwODY1",
            "avatar_url": "https://avatars.githubusercontent.com/u/19590865?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Vyas9296",
            "html_url": "https://github.com/Vyas9296",
            "followers_url": "https://api.github.com/users/Vyas9296/followers",
            "following_url": "https://api.github.com/users/Vyas9296/following{/other_user}",
            "gists_url": "https://api.github.com/users/Vyas9296/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Vyas9296/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Vyas9296/subscriptions",
            "organizations_url": "https://api.github.com/users/Vyas9296/orgs",
            "repos_url": "https://api.github.com/users/Vyas9296/repos",
            "events_url": "https://api.github.com/users/Vyas9296/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Vyas9296/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 8,
        "created_at": "2018-11-19T13:49:44Z",
        "updated_at": "2018-11-27T23:21:21Z",
        "closed_at": "2018-11-27T23:21:21Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/5777",
            "html_url": "https://github.com/tensorflow/models/pull/5777",
            "diff_url": "https://github.com/tensorflow/models/pull/5777.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/5777.patch"
        },
        "body": "Line 219 runtime version updated to 1.9, current version of 1.8 will trigger 'TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'' on the Google Cloud since 1.8 and older does not support this keyword argument.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/5170",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/5170/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/5170/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/5170/events",
        "html_url": "https://github.com/tensorflow/models/pull/5170",
        "id": 353291778,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MjEwMzgwMDkz",
        "number": 5170,
        "title": "Update the runtime version in bash script",
        "user": {
            "login": "wentaoxu415",
            "id": 9408717,
            "node_id": "MDQ6VXNlcjk0MDg3MTc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9408717?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/wentaoxu415",
            "html_url": "https://github.com/wentaoxu415",
            "followers_url": "https://api.github.com/users/wentaoxu415/followers",
            "following_url": "https://api.github.com/users/wentaoxu415/following{/other_user}",
            "gists_url": "https://api.github.com/users/wentaoxu415/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/wentaoxu415/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/wentaoxu415/subscriptions",
            "organizations_url": "https://api.github.com/users/wentaoxu415/orgs",
            "repos_url": "https://api.github.com/users/wentaoxu415/repos",
            "events_url": "https://api.github.com/users/wentaoxu415/events{/privacy}",
            "received_events_url": "https://api.github.com/users/wentaoxu415/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2018-08-23T09:10:42Z",
        "updated_at": "2018-08-23T18:44:10Z",
        "closed_at": "2018-08-23T18:44:10Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/5170",
            "html_url": "https://github.com/tensorflow/models/pull/5170",
            "diff_url": "https://github.com/tensorflow/models/pull/5170.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/5170.patch"
        },
        "body": "The bash script to submit training job for pets detection has runtime-version of 1.8. This will trigger `TypeError: non_max_suppression() got an unexpected keyword argument 'score_threshold'` on the Google Cloud since 1.8 and older does not support this keyword argument. Therefore, update this runtime version to 1.9, which is the most recent runtime version that is published on June 27, 2018. \r\n\r\nSee \r\nhttps://github.com/tensorflow/models/issues/5056\r\nhttps://cloud.google.com/ml-engine/docs/tensorflow/runtime-version-list",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/3810",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/3810/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/3810/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/3810/events",
        "html_url": "https://github.com/tensorflow/models/pull/3810",
        "id": 309912767,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTc4NDQ4Nzcz",
        "number": 3810,
        "title": "fixed dimension compatibility issue for numpy",
        "user": {
            "login": "ziyin-dl",
            "id": 8291536,
            "node_id": "MDQ6VXNlcjgyOTE1MzY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8291536?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ziyin-dl",
            "html_url": "https://github.com/ziyin-dl",
            "followers_url": "https://api.github.com/users/ziyin-dl/followers",
            "following_url": "https://api.github.com/users/ziyin-dl/following{/other_user}",
            "gists_url": "https://api.github.com/users/ziyin-dl/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ziyin-dl/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ziyin-dl/subscriptions",
            "organizations_url": "https://api.github.com/users/ziyin-dl/orgs",
            "repos_url": "https://api.github.com/users/ziyin-dl/repos",
            "events_url": "https://api.github.com/users/ziyin-dl/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ziyin-dl/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2018-03-29T21:40:15Z",
        "updated_at": "2018-03-29T23:13:35Z",
        "closed_at": "2018-03-29T23:13:35Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/3810",
            "html_url": "https://github.com/tensorflow/models/pull/3810",
            "diff_url": "https://github.com/tensorflow/models/pull/3810.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/3810.patch"
        },
        "body": "The original code passes a dimension object to tf.reshape(), which is not recognized with error. This pull request casts the dimension object to int to fix this problem. The stack trace of the original code is attached below:\r\n\r\n\r\n  File \"/home/models/tutorials/image/cifar10/cifar10.py\", line 243, in inference\r\n    reshape = tf.reshape(pool2, [images.get_shape()[0], -1])\r\n  File \"/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py\", line 2619, in reshape\r\n    name=name)\r\n  File \"/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py\", line 493, in apply_op\r\n    raise err\r\nTypeError: Failed to convert object of type <type 'list'> to Tensor. Contents: [Dimension(128), -1]. Consider casting elements to a supported type.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/1532",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/1532/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/1532/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/1532/events",
        "html_url": "https://github.com/tensorflow/models/pull/1532",
        "id": 233836783,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTI0MTUwMDA3",
        "number": 1532,
        "title": "Fixed calls to concat and convolution2d",
        "user": {
            "login": "andrewgilbert12",
            "id": 16242142,
            "node_id": "MDQ6VXNlcjE2MjQyMTQy",
            "avatar_url": "https://avatars.githubusercontent.com/u/16242142?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/andrewgilbert12",
            "html_url": "https://github.com/andrewgilbert12",
            "followers_url": "https://api.github.com/users/andrewgilbert12/followers",
            "following_url": "https://api.github.com/users/andrewgilbert12/following{/other_user}",
            "gists_url": "https://api.github.com/users/andrewgilbert12/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/andrewgilbert12/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/andrewgilbert12/subscriptions",
            "organizations_url": "https://api.github.com/users/andrewgilbert12/orgs",
            "repos_url": "https://api.github.com/users/andrewgilbert12/repos",
            "events_url": "https://api.github.com/users/andrewgilbert12/events{/privacy}",
            "received_events_url": "https://api.github.com/users/andrewgilbert12/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2017-06-06T09:49:02Z",
        "updated_at": "2017-06-06T22:03:52Z",
        "closed_at": "2017-06-06T19:40:32Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/1532",
            "html_url": "https://github.com/tensorflow/models/pull/1532",
            "diff_url": "https://github.com/tensorflow/models/pull/1532.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/1532.patch"
        },
        "body": "When attempting to run the adversarial crypto model, I got the following errors:\r\n\r\n```\r\nline 302, in _AssertCompatible\r\n    (dtype.name, repr(mismatch), type(mismatch).__name__))\r\nTypeError: Expected int32, got list containing Tensors of type '_Message' instead.\r\nline 126, in model\r\n```\r\n\r\n```\r\n    [tf.contrib.layers.fully_connected, tf.contrib.layers.convolution],\r\nAttributeError: 'module' object has no attribute 'convolution'\r\n```\r\n\r\nIt appears that the arguments for tf.concat were in the opposite order of the API documentation, and that the \"tf.contrib.layers.convolution2d\" method was called as \"convolution\". I have corrected both of these issues in this pull request.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/1045",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/1045/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/1045/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/1045/events",
        "html_url": "https://github.com/tensorflow/models/pull/1045",
        "id": 209051120,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTA3MTIyNjgy",
        "number": 1045,
        "title": "Fix division changing dtype to float in python3",
        "user": {
            "login": "ScottSWu",
            "id": 3599407,
            "node_id": "MDQ6VXNlcjM1OTk0MDc=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3599407?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ScottSWu",
            "html_url": "https://github.com/ScottSWu",
            "followers_url": "https://api.github.com/users/ScottSWu/followers",
            "following_url": "https://api.github.com/users/ScottSWu/following{/other_user}",
            "gists_url": "https://api.github.com/users/ScottSWu/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ScottSWu/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ScottSWu/subscriptions",
            "organizations_url": "https://api.github.com/users/ScottSWu/orgs",
            "repos_url": "https://api.github.com/users/ScottSWu/repos",
            "events_url": "https://api.github.com/users/ScottSWu/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ScottSWu/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2017-02-21T06:11:12Z",
        "updated_at": "2017-02-22T01:05:26Z",
        "closed_at": "2017-02-22T01:05:21Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/1045",
            "html_url": "https://github.com/tensorflow/models/pull/1045",
            "diff_url": "https://github.com/tensorflow/models/pull/1045.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/1045.patch"
        },
        "body": "Running the compression encoder example in python3 causes the error:\r\n`TypeError: Expected an input array of integer or boolean data type`\r\n\r\n`int_codes` is divided by 2, but in python3 this converts it from an `int8` to `float64` array.\r\n\r\nI am running the gpu version of tensorflow on Windows 10.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/777",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/777/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/777/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/777/events",
        "html_url": "https://github.com/tensorflow/models/pull/777",
        "id": 196722449,
        "node_id": "MDExOlB1bGxSZXF1ZXN0OTg3ODQ3MzY=",
        "number": 777,
        "title": "Fix the error of \"TypeError: ones_initializer() got multiple values for keyword argument 'dtype'\".",
        "user": {
            "login": "yuefengz",
            "id": 1647833,
            "node_id": "MDQ6VXNlcjE2NDc4MzM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1647833?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/yuefengz",
            "html_url": "https://github.com/yuefengz",
            "followers_url": "https://api.github.com/users/yuefengz/followers",
            "following_url": "https://api.github.com/users/yuefengz/following{/other_user}",
            "gists_url": "https://api.github.com/users/yuefengz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/yuefengz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yuefengz/subscriptions",
            "organizations_url": "https://api.github.com/users/yuefengz/orgs",
            "repos_url": "https://api.github.com/users/yuefengz/repos",
            "events_url": "https://api.github.com/users/yuefengz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/yuefengz/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2016-12-20T16:48:28Z",
        "updated_at": "2016-12-21T07:52:22Z",
        "closed_at": "2016-12-21T07:52:22Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/777",
            "html_url": "https://github.com/tensorflow/models/pull/777",
            "diff_url": "https://github.com/tensorflow/models/pull/777.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/777.patch"
        },
        "body": "Without the change, when I run the inception model with command \r\n  ```\r\n  bazel-bin/inception/imagenet_train --num_gpus=1 --batch_size=32 --train_dir=/tmp/imagenet_train --data_dir=/tmp/imagenet-data\r\n  ```\r\nit would fail with the error\r\n  ```\r\n  Traceback (most recent call last):\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py\", line 41, in <module>\r\n    tf.app.run()\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py\", line 43, in run\r\n    sys.exit(main(sys.argv[:1] + flags_passthrough))\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/imagenet_train.py\", line 37, in main\r\n    inception_train.train(dataset)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py\", line 239, in train\r\n    scope)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_train.py\", line 108, in _tower_loss\r\n    scope=scope)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/inception_model.py\", line 87, in inference\r\n    scope=scope)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/inception_model.py\", line 87, in inception_v3\r\n    scope='conv0')\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/scopes.py\", line 155, in func_with_args\r\n    return func(*args, **current_args)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/ops.py\", line 234, in conv2d\r\n    outputs = batch_norm(conv, **batch_norm_params)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/scopes.py\", line 155, in func_with_args\r\n    return func(*args, **current_args)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/ops.py\", line 111, in batch_norm\r\n    collections=moving_collections)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/scopes.py\", line 155, in func_with_args\r\n    return func(*args, **current_args)\r\n  File \"/home/ubuntu/2nd/models/inception/bazel-bin/inception/imagenet_train.runfiles/inception/inception/slim/variables.py\", line 289, in variable\r\n    trainable=trainable, collections=collections)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 1024, in get_variable\r\n    custom_getter=custom_getter)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 850, in get_variable\r\n    custom_getter=custom_getter)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 346, in get_variable\r\n    validate_shape=validate_shape)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 331, in _true_getter\r\n    caching_device=caching_device, validate_shape=validate_shape)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 677, in _get_single_variable\r\n    expected_shape=shape)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py\", line 224, in __init__\r\n    expected_shape=expected_shape)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py\", line 327, in _init_from_args\r\n    initial_value(), name=\"initial_value\", dtype=dtype)\r\n  File \"/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py\", line 665, in <lambda>\r\n    shape.as_list(), dtype=dtype, partition_info=partition_info)\r\nTypeError: ones_initializer() got multiple values for keyword argument 'dtype'\r\n  ```",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/556",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/556/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/556/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/556/events",
        "html_url": "https://github.com/tensorflow/models/pull/556",
        "id": 183705355,
        "node_id": "MDExOlB1bGxSZXF1ZXN0ODk4Mjg4OTE=",
        "number": 556,
        "title": "Fix end point collection to return a dict",
        "user": {
            "login": "rohitgirdhar",
            "id": 1893429,
            "node_id": "MDQ6VXNlcjE4OTM0Mjk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1893429?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rohitgirdhar",
            "html_url": "https://github.com/rohitgirdhar",
            "followers_url": "https://api.github.com/users/rohitgirdhar/followers",
            "following_url": "https://api.github.com/users/rohitgirdhar/following{/other_user}",
            "gists_url": "https://api.github.com/users/rohitgirdhar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/rohitgirdhar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rohitgirdhar/subscriptions",
            "organizations_url": "https://api.github.com/users/rohitgirdhar/orgs",
            "repos_url": "https://api.github.com/users/rohitgirdhar/repos",
            "events_url": "https://api.github.com/users/rohitgirdhar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/rohitgirdhar/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 337864321,
                "node_id": "MDU6TGFiZWwzMzc4NjQzMjE=",
                "url": "https://api.github.com/repos/tensorflow/models/labels/cla:%20yes",
                "name": "cla: yes",
                "color": "83c1fc",
                "default": false,
                "description": ""
            }
        ],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2016-10-18T14:36:54Z",
        "updated_at": "2016-10-21T05:39:19Z",
        "closed_at": "2016-10-21T05:39:16Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/556",
            "html_url": "https://github.com/tensorflow/models/pull/556",
            "diff_url": "https://github.com/tensorflow/models/pull/556.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/556.patch"
        },
        "body": "Fixes the TF slim models to be compatible with the change in TF 0.11 (https://github.com/tensorflow/tensorflow/commit/5247ebbe24465563bdd4ef46f1cecc34f256f76b)\n\nOtherwise, running vgg/alexnet etc models gives the following error:\n\n``` txt\nend_points = dict(tf.get_collection(end_points_collection))\nTypeError: cannot convert dictionary update sequence element #0 to a sequence\n```\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/36",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/36/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/36/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/36/events",
        "html_url": "https://github.com/tensorflow/models/pull/36",
        "id": 144476063,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjQ1NzY4OTI=",
        "number": 36,
        "title": "Using a `tf.Tensor` as a Python `bool` is not allowed",
        "user": {
            "login": "argszero",
            "id": 52026,
            "node_id": "MDQ6VXNlcjUyMDI2",
            "avatar_url": "https://avatars.githubusercontent.com/u/52026?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/argszero",
            "html_url": "https://github.com/argszero",
            "followers_url": "https://api.github.com/users/argszero/followers",
            "following_url": "https://api.github.com/users/argszero/following{/other_user}",
            "gists_url": "https://api.github.com/users/argszero/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/argszero/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/argszero/subscriptions",
            "organizations_url": "https://api.github.com/users/argszero/orgs",
            "repos_url": "https://api.github.com/users/argszero/repos",
            "events_url": "https://api.github.com/users/argszero/events{/privacy}",
            "received_events_url": "https://api.github.com/users/argszero/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "shlens",
            "id": 13385191,
            "node_id": "MDQ6VXNlcjEzMzg1MTkx",
            "avatar_url": "https://avatars.githubusercontent.com/u/13385191?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/shlens",
            "html_url": "https://github.com/shlens",
            "followers_url": "https://api.github.com/users/shlens/followers",
            "following_url": "https://api.github.com/users/shlens/following{/other_user}",
            "gists_url": "https://api.github.com/users/shlens/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/shlens/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shlens/subscriptions",
            "organizations_url": "https://api.github.com/users/shlens/orgs",
            "repos_url": "https://api.github.com/users/shlens/repos",
            "events_url": "https://api.github.com/users/shlens/events{/privacy}",
            "received_events_url": "https://api.github.com/users/shlens/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "shlens",
                "id": 13385191,
                "node_id": "MDQ6VXNlcjEzMzg1MTkx",
                "avatar_url": "https://avatars.githubusercontent.com/u/13385191?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/shlens",
                "html_url": "https://github.com/shlens",
                "followers_url": "https://api.github.com/users/shlens/followers",
                "following_url": "https://api.github.com/users/shlens/following{/other_user}",
                "gists_url": "https://api.github.com/users/shlens/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/shlens/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/shlens/subscriptions",
                "organizations_url": "https://api.github.com/users/shlens/orgs",
                "repos_url": "https://api.github.com/users/shlens/repos",
                "events_url": "https://api.github.com/users/shlens/events{/privacy}",
                "received_events_url": "https://api.github.com/users/shlens/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 7,
        "created_at": "2016-03-30T06:19:17Z",
        "updated_at": "2016-08-18T20:24:20Z",
        "closed_at": "2016-04-01T02:22:50Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/36",
            "html_url": "https://github.com/tensorflow/models/pull/36",
            "diff_url": "https://github.com/tensorflow/models/pull/36.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/36.patch"
        },
        "body": "raise TypeError(\"Using a `tf.Tensor` as a Python `bool` is not allowed. \"\nTypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/39",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/39/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/39/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/39/events",
        "html_url": "https://github.com/tensorflow/models/pull/39",
        "id": 145892855,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjUyNTM3Mzk=",
        "number": 39,
        "title": "Fix issue in neural_gpu.py where TypeError is raised.",
        "user": {
            "login": "orionr",
            "id": 79994,
            "node_id": "MDQ6VXNlcjc5OTk0",
            "avatar_url": "https://avatars.githubusercontent.com/u/79994?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/orionr",
            "html_url": "https://github.com/orionr",
            "followers_url": "https://api.github.com/users/orionr/followers",
            "following_url": "https://api.github.com/users/orionr/following{/other_user}",
            "gists_url": "https://api.github.com/users/orionr/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/orionr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/orionr/subscriptions",
            "organizations_url": "https://api.github.com/users/orionr/orgs",
            "repos_url": "https://api.github.com/users/orionr/repos",
            "events_url": "https://api.github.com/users/orionr/events{/privacy}",
            "received_events_url": "https://api.github.com/users/orionr/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": {
            "login": "lukaszkaiser",
            "id": 684901,
            "node_id": "MDQ6VXNlcjY4NDkwMQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/684901?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lukaszkaiser",
            "html_url": "https://github.com/lukaszkaiser",
            "followers_url": "https://api.github.com/users/lukaszkaiser/followers",
            "following_url": "https://api.github.com/users/lukaszkaiser/following{/other_user}",
            "gists_url": "https://api.github.com/users/lukaszkaiser/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lukaszkaiser/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lukaszkaiser/subscriptions",
            "organizations_url": "https://api.github.com/users/lukaszkaiser/orgs",
            "repos_url": "https://api.github.com/users/lukaszkaiser/repos",
            "events_url": "https://api.github.com/users/lukaszkaiser/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lukaszkaiser/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "lukaszkaiser",
                "id": 684901,
                "node_id": "MDQ6VXNlcjY4NDkwMQ==",
                "avatar_url": "https://avatars.githubusercontent.com/u/684901?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lukaszkaiser",
                "html_url": "https://github.com/lukaszkaiser",
                "followers_url": "https://api.github.com/users/lukaszkaiser/followers",
                "following_url": "https://api.github.com/users/lukaszkaiser/following{/other_user}",
                "gists_url": "https://api.github.com/users/lukaszkaiser/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lukaszkaiser/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lukaszkaiser/subscriptions",
                "organizations_url": "https://api.github.com/users/lukaszkaiser/orgs",
                "repos_url": "https://api.github.com/users/lukaszkaiser/repos",
                "events_url": "https://api.github.com/users/lukaszkaiser/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lukaszkaiser/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 1,
        "created_at": "2016-04-05T05:40:00Z",
        "updated_at": "2016-04-06T06:48:56Z",
        "closed_at": "2016-04-06T06:48:18Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/39",
            "html_url": "https://github.com/tensorflow/models/pull/39",
            "diff_url": "https://github.com/tensorflow/models/pull/39.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/39.patch"
        },
        "body": "- `python neural_gpu_trainer.py --task=rev` raises the following TypeError:\n  \n  File \u201c..models/neural_gpu/neural_gpu.py\", line 26, in conv_linear\n    assert args\n  File \u201c..tensorflow/python/framework/ops.py\", line 475, in **nonzero**\n    raise TypeError(\"Using a `tf.Tensor` as a Python `bool` is not allowed. \"\n  TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/tensorflow/models/issues/165",
        "repository_url": "https://api.github.com/repos/tensorflow/models",
        "labels_url": "https://api.github.com/repos/tensorflow/models/issues/165/labels{/name}",
        "comments_url": "https://api.github.com/repos/tensorflow/models/issues/165/comments",
        "events_url": "https://api.github.com/repos/tensorflow/models/issues/165/events",
        "html_url": "https://github.com/tensorflow/models/pull/165",
        "id": 157758484,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NzIwNzczMTU=",
        "number": 165,
        "title": "Import scipy.ndimage before tensorflow to fix jpeg load.",
        "user": {
            "login": "elezar",
            "id": 931393,
            "node_id": "MDQ6VXNlcjkzMTM5Mw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/931393?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/elezar",
            "html_url": "https://github.com/elezar",
            "followers_url": "https://api.github.com/users/elezar/followers",
            "following_url": "https://api.github.com/users/elezar/following{/other_user}",
            "gists_url": "https://api.github.com/users/elezar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/elezar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/elezar/subscriptions",
            "organizations_url": "https://api.github.com/users/elezar/orgs",
            "repos_url": "https://api.github.com/users/elezar/repos",
            "events_url": "https://api.github.com/users/elezar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/elezar/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 1,
        "created_at": "2016-05-31T20:07:37Z",
        "updated_at": "2016-06-02T21:01:57Z",
        "closed_at": "2016-06-02T21:01:57Z",
        "author_association": "NONE",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/tensorflow/models/pulls/165",
            "html_url": "https://github.com/tensorflow/models/pull/165",
            "diff_url": "https://github.com/tensorflow/models/pull/165.diff",
            "patch_url": "https://github.com/tensorflow/models/pull/165.patch"
        },
        "body": "When importing tensorflow before scipi.ndimage and running the\nexample in a docker container, the following error is given:\n\n```\n % python example.py\nTraceback (most recent call last):\n  File \"example.py\", line 25, in <module>\n    im = im / 255.\nTypeError: unsupported operand type(s) for /: 'instance' and 'float'\n```\n\nThis only happens for 'cat.jpg'. When converting the image to a '.png'\nfile, the example runs as expected.\n\nWhen swapping the imports around so that scipy.ndimage is imported\nBEFORE tensorflow, both 'jpg' and 'png' files work.\n",
        "performed_via_github_app": null,
        "score": 1.0
    }
]