[
    {
        "url": "https://api.github.com/repos/psf/requests/issues/4683",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/4683/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/4683/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/4683/events",
        "html_url": "https://github.com/psf/requests/pull/4683",
        "id": 331768289,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTk0NDE4ODg4",
        "number": 4683,
        "title": "Do not alter status_codes docstring if it is None",
        "user": {
            "login": "martindurant",
            "id": 6042212,
            "node_id": "MDQ6VXNlcjYwNDIyMTI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6042212?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/martindurant",
            "html_url": "https://github.com/martindurant",
            "followers_url": "https://api.github.com/users/martindurant/followers",
            "following_url": "https://api.github.com/users/martindurant/following{/other_user}",
            "gists_url": "https://api.github.com/users/martindurant/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/martindurant/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/martindurant/subscriptions",
            "organizations_url": "https://api.github.com/users/martindurant/orgs",
            "repos_url": "https://api.github.com/users/martindurant/repos",
            "events_url": "https://api.github.com/users/martindurant/events{/privacy}",
            "received_events_url": "https://api.github.com/users/martindurant/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2018-06-12T21:55:41Z",
        "updated_at": "2018-06-13T15:24:59Z",
        "closed_at": "2018-06-13T15:24:46Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/4683",
            "html_url": "https://github.com/psf/requests/pull/4683",
            "diff_url": "https://github.com/psf/requests/pull/4683.diff",
            "patch_url": "https://github.com/psf/requests/pull/4683.patch"
        },
        "body": "Following https://github.com/requests/requests/pull/4394/files, with PYTHONOPTIMIZE=2, the current code breaks with TypeError due to None as the docstring. This broke dask tests https://github.com/dask/dask/pull/3594 .",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/psf/requests/issues/4723",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/4723/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/4723/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/4723/events",
        "html_url": "https://github.com/psf/requests/pull/4723",
        "id": 338753329,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTk5NjA3OTE3",
        "number": 4723,
        "title": "Fix assumed hostname when using a 'file' URI scheme adapter",
        "user": {
            "login": "kalefranz",
            "id": 1418419,
            "node_id": "MDQ6VXNlcjE0MTg0MTk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1418419?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/kalefranz",
            "html_url": "https://github.com/kalefranz",
            "followers_url": "https://api.github.com/users/kalefranz/followers",
            "following_url": "https://api.github.com/users/kalefranz/following{/other_user}",
            "gists_url": "https://api.github.com/users/kalefranz/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/kalefranz/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kalefranz/subscriptions",
            "organizations_url": "https://api.github.com/users/kalefranz/orgs",
            "repos_url": "https://api.github.com/users/kalefranz/repos",
            "events_url": "https://api.github.com/users/kalefranz/events{/privacy}",
            "received_events_url": "https://api.github.com/users/kalefranz/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 5,
        "created_at": "2018-07-05T23:04:26Z",
        "updated_at": "2018-08-13T16:54:34Z",
        "closed_at": "2018-08-13T16:54:33Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/4723",
            "html_url": "https://github.com/psf/requests/pull/4723",
            "diff_url": "https://github.com/psf/requests/pull/4723.diff",
            "patch_url": "https://github.com/psf/requests/pull/4723.patch"
        },
        "body": "Commit 2255c34a65b5b1353004dc8d49cc397cd794ec15 in https://github.com/requests/requests/pull/4427 makes the assumption that all URLs have hostnames.  Or perhaps the assumption was that `urlparse()` returns an empty string for the `hostname` attribute rather than `None`.  Either way, the assumption blows up both for `is_ipv4_address(parsed.hostname)` and also for\r\n\r\n```python\r\nhost_with_port = parsed.hostname\r\nif parsed.port:\r\n    host_with_port += ':{0}'.format(parsed.port)\r\n```\r\n\r\nwhen `parsed.hostname` is `None`.  Example circumstances of where this all blows up is when a `NO_PROXY` environment variable is set during use of something like conda's [adapter](https://github.com/conda/conda/blob/4.5.5/conda/gateways/connection/adapters/localfs.py) to handle `file:///` urls.  It results in a stack trace like\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/home/circleci/conda/tests/gateways/test_connection.py\", line 62, in test_local_file_adapter_200\r\n    r = session.get(test_url)\r\n  File \"/opt/conda/lib/python3.6/site-packages/requests/sessions.py\", line 525, in get\r\n    return self.request('GET', url, **kwargs)\r\n  File \"/opt/conda/lib/python3.6/site-packages/requests/sessions.py\", line 503, in request\r\n    prep.url, proxies, stream, verify, cert\r\n  File \"/opt/conda/lib/python3.6/site-packages/requests/sessions.py\", line 676, in merge_environment_settings\r\n    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)\r\n  File \"/opt/conda/lib/python3.6/site-packages/requests/utils.py\", line 760, in get_environ_proxies\r\n    if should_bypass_proxies(url, no_proxy=no_proxy):\r\n  File \"/opt/conda/lib/python3.6/site-packages/requests/utils.py\", line 716, in should_bypass_proxies\r\n    if is_ipv4_address(parsed.hostname):\r\n  File \"/opt/conda/lib/python3.6/site-packages/requests/utils.py\", line 640, in is_ipv4_address\r\n    socket.inet_aton(string_ip)\r\nTypeError: inet_aton() argument 1 must be str, not None\r\n```\r\n\r\nI *think* the correct solution here is to just return `True` in the `should_bypass_proxies()` function when there is no hostname in the URL.  Definitely know that sending `None` to `inet_aton(string_ip)` or trying to add `None` to a port string definitely isn't correct.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/psf/requests/issues/4240",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/4240/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/4240/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/4240/events",
        "html_url": "https://github.com/psf/requests/pull/4240",
        "id": 249731154,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTM1NDA2NTU5",
        "number": 4240,
        "title": "Adding header name to exception",
        "user": {
            "login": "mgasvoda",
            "id": 25228167,
            "node_id": "MDQ6VXNlcjI1MjI4MTY3",
            "avatar_url": "https://avatars.githubusercontent.com/u/25228167?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mgasvoda",
            "html_url": "https://github.com/mgasvoda",
            "followers_url": "https://api.github.com/users/mgasvoda/followers",
            "following_url": "https://api.github.com/users/mgasvoda/following{/other_user}",
            "gists_url": "https://api.github.com/users/mgasvoda/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mgasvoda/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mgasvoda/subscriptions",
            "organizations_url": "https://api.github.com/users/mgasvoda/orgs",
            "repos_url": "https://api.github.com/users/mgasvoda/repos",
            "events_url": "https://api.github.com/users/mgasvoda/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mgasvoda/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 6,
        "created_at": "2017-08-11T19:49:57Z",
        "updated_at": "2017-08-12T14:41:34Z",
        "closed_at": "2017-08-12T14:41:28Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/4240",
            "html_url": "https://github.com/psf/requests/pull/4240",
            "diff_url": "https://github.com/psf/requests/pull/4240.diff",
            "patch_url": "https://github.com/psf/requests/pull/4240.patch"
        },
        "body": "Adds the name of the header to the invalid header exception raised on TypeError.\r\n\r\nFixes #4239 ",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/psf/requests/issues/3873",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/3873/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/3873/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/3873/events",
        "html_url": "https://github.com/psf/requests/pull/3873",
        "id": 207537708,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MTA2MTIwMzE0",
        "number": 3873,
        "title": "properly handled failed seek",
        "user": {
            "login": "nateprewitt",
            "id": 5271761,
            "node_id": "MDQ6VXNlcjUyNzE3NjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5271761?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nateprewitt",
            "html_url": "https://github.com/nateprewitt",
            "followers_url": "https://api.github.com/users/nateprewitt/followers",
            "following_url": "https://api.github.com/users/nateprewitt/following{/other_user}",
            "gists_url": "https://api.github.com/users/nateprewitt/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nateprewitt/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nateprewitt/subscriptions",
            "organizations_url": "https://api.github.com/users/nateprewitt/orgs",
            "repos_url": "https://api.github.com/users/nateprewitt/repos",
            "events_url": "https://api.github.com/users/nateprewitt/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nateprewitt/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 6,
        "created_at": "2017-02-14T14:54:52Z",
        "updated_at": "2017-02-14T16:13:01Z",
        "closed_at": "2017-02-14T15:43:19Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/3873",
            "html_url": "https://github.com/psf/requests/pull/3873",
            "diff_url": "https://github.com/psf/requests/pull/3873.diff",
            "patch_url": "https://github.com/psf/requests/pull/3873.patch"
        },
        "body": "This is a minor bug in the way we're handling exceptions for `super_len` in `prepare_body`. The mocked `seek` method wasn't created with the optional `whence` parameter and was failing with a `TypeError` when called. A legacy exception block for the older version of `super_len` caught this and made it appear the test was passing.\r\n\r\nThis commit will wrap the seek->tell->seek process in the appropriate exceptions and fix the test.\r\n\r\nI think there's two things that may need further discussion though. The first minor one being, we've been using `super_len` in `prepare_content_length` without this broad exception block from `prepare_body` for two releases without issue. I'm going to suggest we remove it from `prepare_body` because I don't think these exceptions can be raised from `super_len` any longer, except in cases we probably don't want them caught.\r\n\r\nThe second is, if we seek to the end of a file and fail on the `tell` or `seek` back to the original position, do we want to actually send the request? At that point, we'd probably want to raise an exception, right? This probably is something for 3.0.0 since it will be breaking, but wanted to address it before we merge this.",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/psf/requests/issues/3390",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/3390/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/3390/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/3390/events",
        "html_url": "https://github.com/psf/requests/pull/3390",
        "id": 164333769,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NzY2MTI4OTU=",
        "number": 3390,
        "title": "Defining header value type requirements and tests",
        "user": {
            "login": "nateprewitt",
            "id": 5271761,
            "node_id": "MDQ6VXNlcjUyNzE3NjE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5271761?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nateprewitt",
            "html_url": "https://github.com/nateprewitt",
            "followers_url": "https://api.github.com/users/nateprewitt/followers",
            "following_url": "https://api.github.com/users/nateprewitt/following{/other_user}",
            "gists_url": "https://api.github.com/users/nateprewitt/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nateprewitt/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nateprewitt/subscriptions",
            "organizations_url": "https://api.github.com/users/nateprewitt/orgs",
            "repos_url": "https://api.github.com/users/nateprewitt/repos",
            "events_url": "https://api.github.com/users/nateprewitt/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nateprewitt/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 2,
        "created_at": "2016-07-07T15:13:22Z",
        "updated_at": "2016-07-07T16:20:04Z",
        "closed_at": "2016-07-07T16:20:03Z",
        "author_association": "MEMBER",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/3390",
            "html_url": "https://github.com/psf/requests/pull/3390",
            "diff_url": "https://github.com/psf/requests/pull/3390.diff",
            "patch_url": "https://github.com/psf/requests/pull/3390.patch"
        },
        "body": "Currently a non-string/bytes value will cause `pat.match(value)` to raise a TypeError from `re`. I'm proposing catching this exception and raising it as a more descriptive `InvalidHeader` instead, so that it's clear we're intending this to happen.\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/psf/requests/issues/3368",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/3368/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/3368/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/3368/events",
        "html_url": "https://github.com/psf/requests/pull/3368",
        "id": 163293541,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NzU5MDk3ODI=",
        "number": 3368,
        "title": "Allow None value for chunk_size again",
        "user": {
            "login": "joyzheng",
            "id": 1304895,
            "node_id": "MDQ6VXNlcjEzMDQ4OTU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1304895?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/joyzheng",
            "html_url": "https://github.com/joyzheng",
            "followers_url": "https://api.github.com/users/joyzheng/followers",
            "following_url": "https://api.github.com/users/joyzheng/following{/other_user}",
            "gists_url": "https://api.github.com/users/joyzheng/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/joyzheng/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/joyzheng/subscriptions",
            "organizations_url": "https://api.github.com/users/joyzheng/orgs",
            "repos_url": "https://api.github.com/users/joyzheng/repos",
            "events_url": "https://api.github.com/users/joyzheng/events{/privacy}",
            "received_events_url": "https://api.github.com/users/joyzheng/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 3,
        "created_at": "2016-07-01T00:06:42Z",
        "updated_at": "2016-07-01T20:39:05Z",
        "closed_at": "2016-07-01T00:11:01Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/3368",
            "html_url": "https://github.com/psf/requests/pull/3368",
            "diff_url": "https://github.com/psf/requests/pull/3368.diff",
            "patch_url": "https://github.com/psf/requests/pull/3368.patch"
        },
        "body": "Passing in `chunk_size=None` used to be fine, but started raising a `TypeError` following the addition of the type check (#3365)\n",
        "performed_via_github_app": null,
        "score": 1.0
    },
    {
        "url": "https://api.github.com/repos/psf/requests/issues/3179",
        "repository_url": "https://api.github.com/repos/psf/requests",
        "labels_url": "https://api.github.com/repos/psf/requests/issues/3179/labels{/name}",
        "comments_url": "https://api.github.com/repos/psf/requests/issues/3179/comments",
        "events_url": "https://api.github.com/repos/psf/requests/issues/3179/events",
        "html_url": "https://github.com/psf/requests/pull/3179",
        "id": 153160783,
        "node_id": "MDExOlB1bGxSZXF1ZXN0Njg5NjIwMDk=",
        "number": 3179,
        "title": "Fix TypeError when get json-encoded content of a response",
        "user": {
            "login": "messense",
            "id": 1556054,
            "node_id": "MDQ6VXNlcjE1NTYwNTQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1556054?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/messense",
            "html_url": "https://github.com/messense",
            "followers_url": "https://api.github.com/users/messense/followers",
            "following_url": "https://api.github.com/users/messense/following{/other_user}",
            "gists_url": "https://api.github.com/users/messense/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/messense/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/messense/subscriptions",
            "organizations_url": "https://api.github.com/users/messense/orgs",
            "repos_url": "https://api.github.com/users/messense/repos",
            "events_url": "https://api.github.com/users/messense/events{/privacy}",
            "received_events_url": "https://api.github.com/users/messense/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "closed",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 7,
        "created_at": "2016-05-05T03:17:47Z",
        "updated_at": "2016-05-06T12:59:01Z",
        "closed_at": "2016-05-06T12:59:01Z",
        "author_association": "CONTRIBUTOR",
        "active_lock_reason": null,
        "draft": false,
        "pull_request": {
            "url": "https://api.github.com/repos/psf/requests/pulls/3179",
            "html_url": "https://github.com/psf/requests/pull/3179",
            "diff_url": "https://github.com/psf/requests/pull/3179.diff",
            "patch_url": "https://github.com/psf/requests/pull/3179.patch"
        },
        "body": "[`self.content`](https://github.com/kennethreitz/requests/blob/master/requests/models.py#L728) could be `None`, so `len(self.content)` may raise `TypeError: object of type 'NoneType' has no len()`\n",
        "performed_via_github_app": null,
        "score": 1.0
    }
]